### ISSUE TITLE
Solicitação de entrada

### ISSUE THREAD

**Issue by renanxcortes** [sillasgonzaga/rbloggers-BR#2]
Olá Sillas, poderia me incluir no blog? Grande abraço!

**Comment by sillasgonzaga** [comment]
Qual o endereço?

**Comment by renanxcortes** [comment]
Olá Sillas, o que tu te refere como sendo o 'endereço'?

Perdão, ainda sou novo github e não sei como usar direito as ferramentas....

2016-12-24 12:13 GMT-02:00 Sillas Teixeira Gonzaga <notifications@github.com

**Comment by sillasgonzaga** [comment]
Você não quer que eu inclua algum blog no bot? Qual o endereço do blog?

**Comment by renanxcortes** [comment]
Ah sim, é o blog do Neylson:

http://neylsoncrepalde.github.io/

E também o seu, pode ser?

2016-12-24 12:30 GMT-02:00 Sillas Teixeira Gonzaga <notifications@github.com

**Comment by renanxcortes** [comment]
Não é seria para adicionar nenhum outro blog específico.. mas para
recebimento do feed destes blogs que você está agregando

Em 24 de dezembro de 2016 12:35, Renan Xavier <renanxcortes@gmail.com>
escreveu:

**Comment by sillasgonzaga** [comment]
Vc quer o feed do bot, é isso?

Vc pode usar este link: https://twitrss.me/twitter_user_to_rss/?user=rbloggersbr
