### ISSUE TITLE
Análise Macro

### ISSUE THREAD

**Issue by analisemacro** [sillasgonzaga/rbloggers-BR#5]
Peço, por favor, que adicionem o blog da Análise Macro: http://analisemacro.com.br/blog/

**Comment by sillasgonzaga** [comment]
O seu vai demorar um pouco mais que o normal. Tem alguma coisa na formatação do XML do feed do seu blog que tá fazendo o código retornar um erro.

```
> url <- "http://feeds.feedburner.com/analisemacro?format=xml"
> x <- feed.extract(url)
Error: Unable to parse date.
In addition: Warning message:
All formats failed to parse. No formats found.
``` 

Isso não aconteceu com nenhum outro blog até o momento. [Ao que parece](https://github.com/DataWookie/feedeR/issues/3), é um caso específico de alguns blogs.

Para conseguir integrar seu blog ao bot, vou criar um fork do pacote `feedeR` e adicionar uma cláusula de erro para parsear a data dos posts.

**Comment by sillasgonzaga** [comment]
Enquanto eu não consigo uma solução, abri uma [issue](https://github.com/DataWookie/feedeR/issues/5) para o criador do pacote `feedeR`.

**Comment by sillasgonzaga** [comment]
Deu muito trabalho mas consegui! Pra vc ter ideia, tive de modificar o código fonte do pacote `feedeR` apenas para conseguir incluir seu tópico.

Aproveita que vou me mudar pro RJ no próximo mês para me pagar uma cerveja haha.

**Comment by analisemacro** [comment]
Fala Silas, vlw! Tá combinado! Só entrar em contato que a gente marca! rs


Vítor Wilher
MSc in Economics
(21) 96973-8953
www.vitorwilher.com<http://www.vitorwilher.com>
macroeconomia@vitorwilher.com




________________________________
