### ISSUE TITLE
Lista de blogs

### ISSUE THREAD

**Issue by marcosvital** [sillasgonzaga/rbloggers-BR#6]
Olá, Sillas!

Estou organizando uma lista dos blogs brasileiros sobre o R. Confira lá, pode ser uma boa fonte para você adicionar mais blogs aqui no seu projeto.

No meu caso é apenas uma lista simples mesmo, que de repente possa servir como uma central para quem está procurando material sobre o R em português e não sabe por onde começar.

https://github.com/marcosvital/blogs-de-R-no-Brasil

Abraços!

**Comment by sillasgonzaga** [comment]
Que legal cara, vou adicionar sim! No próximo sábado vou adicionar os blogs que vc encontrou. Obrigado!

**Comment by sillasgonzaga** [comment]
Já fiz uma issue para cada blog na sua lista que não estava no bot. Obrigado pela contribuição!
